### ISSUE TITLE
IntroductionToMachineLearning.ipynb of Module 1 is not opening. It is throwing JSON error!

### ISSUE THREAD

**Issue by infinityscience** [MicrosoftLearning/Principles-of-Machine-Learning-Python#4] opened 2018-09-01 11:40 UTC
Hi

Thanks for providing ML course. I tried opening the first file and it does not 

IntroductionToMachineLearning.ipynb of Module 1 is not opening. It is throwing JSON error!

Could you please kindly fix it?

![error_msml_module1](https://user-images.githubusercontent.com/42890557/44945574-449ba580-ade4-11e8-8b90-2ddb86081262.PNG)

**Comment by yazha-MS** [comment] 2018-09-03 10:31
Found that the issue is caused by line 186 for the latest change "\Examine ..... If you want to work around this, you can remove the "\" here  then this notebook will work.

**Comment by Adamus7** [comment] 2018-09-03 15:40
Remove "\" at the beginning of the line 186 resolved the issue.
"Examine ....."

**Comment by StephenElston** [comment] 2018-09-03 16:16
I am sorry you are having problems with opening the notebook. 

I am unable to reproduce this problem, either locally or in Azure Notebooks. What kind of environment are you using?

**Comment by yazha-MS** [comment] 2018-09-04 03:02
@StephenElston Azure Notebooks.

**Comment by StephenElston** [comment] 2018-09-04 03:16
Thanks. It is odd that you have this problem, but it cannot be reproduced otherwise. Please let me know if something like this happens again.

**Comment by TaylorHuang2017** [comment] 2018-09-04 05:52
The problem is reproducible with my Azure notebooks, as well as my local Jupyter notebook @StephenElston

**Comment by infinityscience** [comment] 2018-09-04 15:28
Thanks for your support :)

**Comment by airsky** [comment] 2018-09-05 13:47
Similar issue for me today. 
"Bad notebook format, invalid JSON" when I try to run it after import to azure notebooks.

**Comment by StephenElston** [comment] 2018-09-05 15:01
I was now able to reproduce this problem and fix it. It does indeed seem to be the stray '/' on line 186. 

Thank you for your help and persistence in resolving this problem.

**Closed** 2018-11-19 16:10 UTC
